#!/bin/bash

jupyter labextension install @jupyter-voila/jupyterlab-preview
jupyter serverextension enable voila --sys-prefix
jupyter lab build

# Import the workspace into JupyterLab
jupyter lab workspaces import binder/workspace.json

# jupyter-offlinenotebook is automatically installed by repo2docker.
# Uninstall to avoid conflicts
jupyter labextension uninstall --no-build jupyter-offlinenotebook